# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sum of Single Effect (SuSiE) for group variable selection
#'
#' @param y vector of observations
#' @param X1 1st matrix of covariates
#' @param X2 2nd matrix of covariates
#' @param L number of effects 
#' @param sigma2 default is 0, meaning that the variance of the error term is estimated. It can be fixed to a specific value.
#' @param delta tolerance in the ELBO variation for convergence
#' @param maxIt maximum number of iterations allowed
NULL

#'
#' @return  \code{B1}: \code{p x L} matrix of posterior means of the regression coefficients associated to X1. Each column reports the value of the coefficient for different effects.
#' @return  \code{B2}: \code{p x L} matrix of posterior means of regression coefficients associated to X2. Each column reports the value of the coefficient for different effects.
#' @return  \code{SigmaB1}: \code{p x L} matrix of posterior variances of regression coefficients associated to X1.
#' @return  \code{SigmaB2}: \code{p x L} matrix of posterior variances of regression coefficients associated to X2.
#' @return  \code{alpha}: \code{p x L} matrix of posterior inclusion probabilities. Same for X1 and X2 (group selection)
#' @return  \code{sigma2}: estimated variance of the error term
#' @return  \code{yhat}: fitted values
#' @return  \code{elbo_iter}: sequences of ELBO values until convergence
#' @return  \code{elbo}: value of ELBO at convergence
#' @export
SuSiE_group <- function(y, X1, X2, L, sigma2 = 0, delta = 0.001, maxIt = 100L) {
    .Call(`_CPVS_SuSiE_group`, y, X1, X2, L, sigma2, delta, maxIt)
}

